title: Compiletor and Interpretator on F#
description: created by Zhelanov, Katin, Pavlovsky
theme: just-the-docs


aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
